# Generated by Django 5.2.4 on 2025-07-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liberian',
            new_name='Librarian',
        ),
    ]
